version: '3.9'

services:

  database:
    container_name: database
    build: 
      context: ./docker/database
    restart: always
    volumes:
      - ./database/container:/var/lib/mysql
      - ./database:/database
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - nginxnetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php:/public
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - nginxnetwork

  php:
    build: ./docker/php/
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./php:/public
    expose:
      - 9000
    networks:
      - nginxnetwork
networks:
  nginxnetwork:
