version: '3.9'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./projects:/projects
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - nginxnetwork

  database:
    image: mariadb:10.10
    restart: always
    volumes:
      - ./database/container:/var/lib/mysql
      - ./database:/database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    command: --default-authentication-plugin=mysql_native_password --group_concat_max_len=4294967295 --sql_mode="STRICT_TRANS_TABLES" --default_time_zone=-03:00 --event_scheduler="on" --max_allowed_packet=1073741824
    restart: always
    networks:
      - nginxnetwork

  php:
    container_name: php
    build: ./docker/php/
    volumes:
      - ./projects:/projects
    environment:
      MYSQL_TYPE: "$MYSQL_TYPE"
      MYSQL_HOST: "$MYSQL_HOST"
      MYSQL_DBNAME: "$MYSQL_DBNAME"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    expose:
      - 9000
    restart: always
    networks:
      - nginxnetwork
    
networks:
  nginxnetwork:
